echo "We are trying this practical from linux EC2"
echo "We are from batch-25 and learning git/gihub"
echo "We are learning Branching"
echo "I am learning Git"
echo "Hello, How are you?"
echo "you touch my hairs"
echo "I am learning Git "
echo "shweta why are you not giving me suggestions??"
echo "Hello, How are you?"